### ISSUE TITLE
Error in rmf_traffic_schedule_node

### ISSUE THREAD

**Issue by destkk** [open-rmf/rmf_demos#27]
Hi there. I have tried launching a demo launch file and apparently there is a dispatcher node error which results to failure in launching. I have not edited any of the files from provided by RMF demos and core. May I know what could be the cause of these errors?

```
[INFO] [launch]: All log files can be found below /home/rosuser/.ros/log/2021-04-08-11-23-22-099046-rosuser-4672
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rmf_traffic_schedule-1]: process started with pid [4674]
[INFO] [rmf_traffic_blockade-2]: process started with pid [4676]
[INFO] [door_supervisor-3]: process started with pid [4678]
[INFO] [lift_supervisor-4]: process started with pid [4680]
[INFO] [rmf_task_dispatcher-5]: process started with pid [4682]
[rmf_task_dispatcher-5] ~Initializing Dispatcher Node~
[rmf_task_dispatcher-5] [INFO] [1617852202.374765163] [rmf_dispatcher_node]:  Declared Time Window Param as: 2.000000 secs
[rmf_task_dispatcher-5] [INFO] [1617852202.374846947] [rmf_dispatcher_node]:  Declared Terminated Tasks Max Size Param as: 100
[rmf_task_dispatcher-5] [INFO] [1617852202.381721003] [rmf_dispatcher_node]: Starting task dispatcher node
[rmf_traffic_blockade-2] [INFO] [1617852202.383422101] [rmf_traffic_blockade_node]: Beginning traffic blockade node
[rmf_traffic_schedule-1] [FATAL] [1617852202.495543207] [rmf_traffic_schedule_node]: Failed to correctly load participant registry: yaml-cpp: error at line 915, column 11: bad conversion
[rmf_traffic_schedule-1] 
[rmf_traffic_schedule-1] terminate called after throwing an instance of 'std::runtime_error'
[rmf_traffic_schedule-1]   what():  yaml-cpp: error at line 915, column 11: bad conversion
[ERROR] [rmf_traffic_schedule-1]: process has died [pid 4674, exit code -6, cmd '/home/rosuser/rmf_ws/install/rmf_traffic_ros2/lib/rmf_traffic_ros2/rmf_traffic_schedule --ros-args --params-file /tmp/launch_params_lzwgc264'].

```

**Comment by mxgrey** [comment]
We've seen this issue popping up a few times for various users, but haven't been able to reproduce the issue reliably. This may be an opportunity for us to get some insight on what might be causing it.

Could you do me a favor and look at the contents of a hidden file called `.rmf_schedule_node.yaml` that will live in whatever directory you call `ros2 launch ...` from? (Presumably it will be `~/rmf_ws/.rmf_schedule_node.yaml`).

Then copy/paste the entire contents of that file into a [gist](https://gist.github.com/), create a public gist and link us to it. Or if there's any reason you don't want to share the contents publicly, you could also send me an email with the file's contents, and I'll keep it confidential.

Being able to see the contents of that file might help us identify why this has been happening randomly for some users.

After you've shared the contents with us, you can simply delete that file and then everything should work fine again. You should also consider updating your `rmf_internal_msgs`, `rmf_traffic`, and `rmf_ros2` repos by running `git pull origin main` in each of those folders inside of `~/rmf_ws/src/rmf/`, because it's possible (but not confirmed) that this issue is related [to this bug fix](https://github.com/open-rmf/rmf_ros2/pull/22).
