### ISSUE TITLE
Caddy model fails when increase step size to 0.02 in gz

### ISSUE THREAD

**Issue by youliangtan** [open-rmf/rmf_demos#46]
### Description of the bug
Caddy fails when increases the step size to `0.02` in gazebo. Notice that the model will spawn back to the origin

https://user-images.githubusercontent.com/32189404/118593540-75ada580-b7da-11eb-8daf-1d024f8b149f.mp4

(not sure why the video is not viewable on firefox :disappointed: , try chrome)

### Steps to reproduce the bug

1. `ros2 launch rmf_demos airport_terminal.launch.xml`
2. Run this when launch is completed: `gz physics -s 0.02`

Observe the caddy robot. 

Occasionally will get this error when repeat the above steps:
```bash
[gzclient-14] gzclient: /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:251: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
[ERROR] [gzclient-14]: process has died [pid 5
```

Note that this will not happen when using stepsize 0.01 in gazebo. On ignition, it works perfectly fine.

I tried to remove the `readonly` plugin in the `rmf_demos_assets/models/Caddy`'s `model.sdf` and spawn `caddy` at other location. But this issue still happens. Will require a further look into the model to debug on this.

**Comment by mxgrey** [comment]
This is most likely an internal Gazebo/physics issue rather than anything we're doing with RMF. If I understand correctly, when model states start to get populated with NaNs, Gazebo might fall back to just placing the model at the origin.

NaNs happen when the physics can't manage to solve the constraints in a numerically stable way. Doubling the step size can easily make the physics constraints numerically unstable. I think we'll have to accept that we can't use the caddy model when we want the step size to be `0.02`. Personally I never fiddle with the step size because of precisely this kind of issue.
